/**
 * Catálogo de Radios Peruanas en Vivo
 * Streams oficiales verificados en formato HTTPS / AAC / MP3
 */
const RADIOS_DATA = [
  {
    id: "moda",
    name: "Radio Moda",
    dial: "97.3 FM",
    slogan: "¡Te mueve! Con la mejor música urbana",
    genre: "urbano",
    genreLabel: "Reggaetón & Urbano",
    streamUrl: "https://mdstrm.com/audio/6839e1c82cc4c480fcd318dd/icecast.audio",
    badgeColor: "#ff007f",
    gradient: "linear-gradient(135deg, #ff007f, #7928ca)",
    emoji: "🔥",
    city: "Lima / Nacional"
  },
  {
    id: "rpp",
    name: "RPP Noticias",
    dial: "89.7 FM / 730 AM",
    slogan: "La voz de todo el Perú",
    genre: "noticias",
    genreLabel: "Noticias & Actualidad",
    streamUrl: "https://mdstrm.com/audio/5fab3416b5f9ef165cfab6e9/icecast.audio",
    badgeColor: "#e63946",
    gradient: "linear-gradient(135deg, #d90429, #ef233c)",
    emoji: "📰",
    city: "Nacional"
  },
  {
    id: "studio92",
    name: "Studio 92",
    dial: "92.5 FM",
    slogan: "Primeros en tu música",
    genre: "pop",
    genreLabel: "Pop, Urbano & Electro",
    streamUrl: "https://mdstrm.com/audio/5fada553978fe1080e3ac5ea/icecast.audio",
    badgeColor: "#00f2fe",
    gradient: "linear-gradient(135deg, #00f2fe, #4facfe)",
    emoji: "⚡",
    city: "Lima / Nacional"
  },
  {
    id: "panamericana",
    name: "Radio Panamericana",
    dial: "101.1 FM",
    slogan: "Lo que el Perú quiere escuchar",
    genre: "salsa",
    genreLabel: "Salsa de Oro & Timba",
    streamUrl: "https://mdstrm.com/audio/6598b62dded1380470f4e539/icecast.audio",
    badgeColor: "#f77f00",
    gradient: "linear-gradient(135deg, #f77f00, #fcbf49)",
    emoji: "💃",
    city: "Lima / Nacional"
  },
  {
    id: "ondacero",
    name: "Radio Onda Cero",
    dial: "98.1 FM",
    slogan: "¡Te activa! Lo más pegado de la música urbana",
    genre: "urbano",
    genreLabel: "Urbano & Trap",
    streamUrl: "https://mdstrm.com/audio/5fada54116646e098d97e6a5/icecast.audio",
    badgeColor: "#06d6a0",
    gradient: "linear-gradient(135deg, #06d6a0, #118ab2)",
    emoji: "🎧",
    city: "Lima / Nacional"
  },
  {
    id: "oxigeno",
    name: "Radio Oxígeno",
    dial: "102.1 FM",
    slogan: "Clásicos del Rock & Pop",
    genre: "rock",
    genreLabel: "Rock & Pop 80s y 90s",
    streamUrl: "https://mdstrm.com/audio/5fab0687bcd6c2389ee9480c/icecast.audio",
    badgeColor: "#3a86ff",
    gradient: "linear-gradient(135deg, #3a86ff, #8338ec)",
    emoji: "🎸",
    city: "Lima / Nacional"
  },
  {
    id: "ritmoromantica",
    name: "Ritmo Romántica",
    dial: "93.1 FM",
    slogan: "Tu radio de baladas",
    genre: "baladas",
    genreLabel: "Baladas & Románticas",
    streamUrl: "https://mdstrm.com/audio/6839e2376607bdf6b2fcde27/icecast.audio",
    badgeColor: "#ff4d6d",
    gradient: "linear-gradient(135deg, #ff4d6d, #c9184a)",
    emoji: "💖",
    city: "Lima / Nacional"
  },
  {
    id: "nuevaq",
    name: "Radio Nueva Q",
    dial: "107.1 FM",
    slogan: "¡QQQuieeeen te quiere! La radio de la cumbia",
    genre: "cumbia",
    genreLabel: "Cumbia Peruana",
    streamUrl: "https://mdstrm.com/audio/6839e1f153fcf56d988d5943/icecast.audio",
    badgeColor: "#ffbe0b",
    gradient: "linear-gradient(135deg, #ffbe0b, #fb5607)",
    emoji: "🎺",
    city: "Lima / Nacional"
  },
  {
    id: "radiomar",
    name: "Radiomar Plus",
    dial: "106.3 FM",
    slogan: "¡Vive gozando! La salsa sabrosa del Perú",
    genre: "salsa",
    genreLabel: "Salsa Dura & Romántica",
    streamUrl: "https://mdstrm.com/audio/6839e261d2efddf5bfbc2d3d/icecast.audio",
    badgeColor: "#00b4d8",
    gradient: "linear-gradient(135deg, #00b4d8, #0077b6)",
    emoji: "🌊",
    city: "Lima / Callao"
  },
  {
    id: "karibena",
    name: "Radio Karibeña",
    dial: "94.9 FM",
    slogan: "¡Si suena! Los éxitos de la cumbia elegante",
    genre: "cumbia",
    genreLabel: "Cumbia & Fiesta",
    streamUrl: "https://karibena.egostreaming.pe/radio/6898b6e52d9e088a6de159/",
    badgeColor: "#ff5400",
    gradient: "linear-gradient(135deg, #ff5400, #ff0054)",
    emoji: "🎉",
    city: "Nacional"
  },
  {
    id: "lakalle",
    name: "Radio La Kalle",
    dial: "96.1 FM",
    slogan: "¡Qué te pasa! Salsa, criollo y boleros de oro",
    genre: "salsa",
    genreLabel: "Salsa & Criollismo",
    streamUrl: "https://lakalle.egostreaming.pe/radio/a7b9c3e4567f8d0123456789/",
    badgeColor: "#9d4edd",
    gradient: "linear-gradient(135deg, #9d4edd, #5a189a)",
    emoji: "🎷",
    city: "Lima / Nacional"
  },
  {
    id: "doblenueve",
    name: "Radio Doble Nueve",
    dial: "99.1 FM",
    slogan: "La radio rock del mundo",
    genre: "rock",
    genreLabel: "Rock Alternativo & Indie",
    streamUrl: "https://conectperu.com:7000/stream?icy=http",
    badgeColor: "#0582ca",
    gradient: "linear-gradient(135deg, #0582ca, #006494)",
    emoji: "⚡",
    city: "Lima"
  },
  {
    id: "inolvidable",
    name: "Radio La Inolvidable",
    dial: "93.7 FM",
    slogan: "Tus mejores recuerdos",
    genre: "recuerdo",
    genreLabel: "Música del Recuerdo 70s y 80s",
    streamUrl: "https://mdstrm.com/audio/6839e24cf4eacd81ada4e6b4/icecast.audio",
    badgeColor: "#e07a5f",
    gradient: "linear-gradient(135deg, #e07a5f, #3d405b)",
    emoji: "📻",
    city: "Lima / Nacional"
  },
  {
    id: "felicidad",
    name: "Radio Felicidad",
    dial: "88.9 FM",
    slogan: "La música de tu vida",
    genre: "recuerdo",
    genreLabel: "Boleros & Recuerdos",
    streamUrl: "https://mdstrm.com/audio/5fad731fcf097a068af3c8f7/icecast.audio",
    badgeColor: "#80ed99",
    gradient: "linear-gradient(135deg, #38b000, #007200)",
    emoji: "✨",
    city: "Lima / Nacional"
  },
  {
    id: "planeta",
    name: "Radio Planeta",
    dial: "107.7 FM",
    slogan: "Tu música en inglés",
    genre: "pop",
    genreLabel: "Pop & Hits Internacionales",
    streamUrl: "https://mdstrm.com/audio/6839e274f40e6b9832e37633/icecast.audio",
    badgeColor: "#7209b7",
    gradient: "linear-gradient(135deg, #7209b7, #4cc9f0)",
    emoji: "🌍",
    city: "Lima"
  },
  {
    id: "magica",
    name: "Radio Mágica",
    dial: "88.3 FM",
    slogan: "Discos de oro en inglés",
    genre: "rock",
    genreLabel: "Oldies 60s, 70s y 80s",
    streamUrl: "https://mdstrm.com/audio/6839e28eb3fdc597ac2e2e43/icecast.audio",
    badgeColor: "#f4a261",
    gradient: "linear-gradient(135deg, #f4a261, #e76f51)",
    emoji: "🌟",
    city: "Lima"
  },
  {
    id: "exitosa",
    name: "Radio Exitosa",
    dial: "95.5 FM",
    slogan: "La voz de los que no tienen voz",
    genre: "noticias",
    genreLabel: "Noticias & Debate",
    streamUrl: "https://neptuno-2-audio.mediaserver.digital/79525baf-b0f5-4013-a8bd-3c5c293c6561",
    badgeColor: "#b5179e",
    gradient: "linear-gradient(135deg, #b5179e, #7209b7)",
    emoji: "📢",
    city: "Nacional"
  },
  {
    id: "cumbiamix",
    name: "Radio Cumbia Mix",
    dial: "Online",
    slogan: "Pura cumbia las 24 horas",
    genre: "cumbia",
    genreLabel: "Cumbia y Ritmo",
    streamUrl: "https://mdstrm.com/audio/6598b6ab95a235085823b24f/icecast.audio",
    badgeColor: "#2ec4b6",
    gradient: "linear-gradient(135deg, #2ec4b6, #e71d36)",
    emoji: "🥁",
    city: "Online / Digital"
  }
];
